---
- name: Register a system with Red Hat using `sudo rhc connect`
  hosts: "{{ _hosts }}"
  become: yes
  vars:
    redhat_username: "{{ lookup('env', 'REDHAT_USERNAME') }}"  # Fetch username from environment variable
    redhat_password: "{{ lookup('env', 'REDHAT_PASSWORD') }}"  # Fetch password from environment variable
  tasks:
    - name: Run sudo rhc connect to register the system
      command: >
        sudo rhc connect
      environment:
        RHC_USERNAME: "{{ redhat_username }}"
        RHC_PASSWORD: "{{ redhat_password }}"
      register: output_message

    - name: Display the output of sudo rhc connect
      debug:
        var: output_message.stdout
