---
- name: retrieve hosts with your_tags filter
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
   - name: retrieve vms from your_location
     azure.azcollection.azure_rm_virtualmachine_info:
       tags: "{{ your_tags | default('demo:true') }}"
     register: retrieved_info

   - name: print retrieved_info
     ansible.builtin.debug:
       msg: "{{ retrieved_info }}"